### ISSUE TITLE
How to enlarge signature png in thesis?

### ISSUE THREAD

**Issue by hongwai1920** [wang-chen/thesis_template_ntu#10]
I attempted to insert my own signature png file into the thesis template.
However, the displayed image is too small.
How can I enlarge it? 
I tried \includegraphic but it returns an error.

**Comment by wang-chen** [comment]
I guess your signature png has a large white margin?
You'd better crop you png file to fit your signature.

You may enlarge the display by change [L502](https://github.com/wang-chen/thesis_template_ntu/blob/3bb023cbdb6ce9ead152583d9539289835059754/Thesis.cls#L502), however, it will move down the dashed line and your name (unbalanced with the left date), which looks not good.

**Comment by hongwai1920** [comment]
I modified the L502 to just \makebox[4cm]{#4} so that I can control the scaling of image at the main tex file.
It suits my purpose after such changes.
