### ISSUE TITLE
unclosed open group { found at \end{document} error from

### ISSUE THREAD

**Issue by FangliangBai** [wang-chen/thesis_template_ntu#4]
I upload the template to Overleaf and found this issue:

![image](https://user-images.githubusercontent.com/10924189/59702518-d0ee4c00-91ef-11e9-804f-a92d64415849.png)

Did anyone have the same issue? How did you solve it?

**Comment by wang-chen** [comment]
Hi, I have no compiling issues in overleaf: https://v2.overleaf.com/read/hrjsywqdhccp

**Comment by FangliangBai** [comment]
> Hi, I have no compiling issues in overleaf: https://v2.overleaf.com/read/hrjsywqdhccp

Hi Chen, thank you very much for helping. I opened your shared project and found the same issue in `mythesis.tex` @ line 172.

![image](https://user-images.githubusercontent.com/10924189/59748999-210ef200-9274-11e9-8d61-924d035fd8d1.png)


There is no error output in logs, which is the same as mine.

![image](https://user-images.githubusercontent.com/10924189/59748909-fa50bb80-9273-11e9-93fe-38c5f9b099ef.png)

Please, could you help to solve this problem? I assumed this is just a simple bracket-missing problem but I couldn't figure out where to add the bracket. Thank you for helping.

**Comment by FangliangBai** [comment]
Hi @wang-chen, sorry for digression

**Comment by wang-chen** [comment]
Hi, I have merged a pull request from @BritskNguyen , which solves this problem. For line spacing, a command “\setstretch{1.3}” in the main tex file is used. If you find this problem has been solved. Please close this issue, thanks!

**Comment by FangliangBai** [comment]
Thank you very much for solving this issue.
