### ISSUE TITLE
Statement of Originality has been updated on March 11th 2019

### ISSUE THREAD

**Issue by BritskNguyen** [wang-chen/thesis_template_ntu#6]
The new statement is:

"I hereby certify that the work embodied in this thesis is the result of
original research, is free of plagiarised materials, and has not been
submitted for a higher degree to any other University or Institution."

Please refer to EEE's intranet for more details:
https://eeen40028.eee.ntu.edu.sg/Graduate/forms/Research/Student/PDFs/Thesis_for_Examination/Thesis%20Submission%20Procedure%202019_14-Mar-19.pdf

**Comment by wang-chen** [comment]
Resolved, [pull request 7](https://github.com/wang-chen/thesis_template_ntu/pull/7)
