### ISSUE TITLE
How to make all theorems italic?

### ISSUE THREAD

**Issue by hongwai1920** [wang-chen/thesis_template_ntu#8]
I realize that all fonts in theorem environment are not italic.
How to italize them without manually changing all theorems one by one?

**Comment by wang-chen** [comment]
I have updated the theorem styles.

I have also provided more examples in [Chapter 2](https://github.com/wang-chen/thesis_template_ntu/blob/a3e41a86342140ac16e3684d64d0ee6542422cda/Chapters/Chapter2.tex#L23).

The amsthm package has three separate predefined styles:

\theoremstyle{plain} is the default. it sets the text in italic and adds extra space above and below the \newtheorems listed below it in the input. it is recommended for theorems, corollaries, lemmas, propositions, conjectures, criteria, and (possibly; depends on the subject area) algorithms.

\theoremstyle{definition} adds extra space above and below, but sets the text in roman. it is recommended for definitions, conditions, problems, and examples.

\theoremstyle{remark} is set in roman, with no additional space above or below. it is recommended for remarks, notes, notation, claims, summaries, acknowledgments, cases, and conclusions.

I have set them [here](https://github.com/wang-chen/thesis_template_ntu/blob/a3e41a86342140ac16e3684d64d0ee6542422cda/Thesis.cls#L106) accordingly.

You may see the changes visually at [Overleaf project](https://www.overleaf.com/read/hrjsywqdhccp).

**Comment by wang-chen** [comment]
Note that theorems, corollaries, and lemmas use the same counter, as expected.
You may change them to use separate counters.

For example, change [this line](https://github.com/wang-chen/thesis_template_ntu/blob/a3e41a86342140ac16e3684d64d0ee6542422cda/Thesis.cls#L110).

From 
            
    \newtheorem{lemma}[theorem]{Lemma}

to
           
    \newtheorem{lemma}{Lemma}[chapter]
