### ISSUE TITLE
Avoid displaying numbers with hyperlink at bibliography section

### ISSUE THREAD

**Issue by hongwai1920** [wang-chen/thesis_template_ntu#9]
At each reference in the section bibliography, there are numbers with hyperlink, which when clicked, will lead readers to where the reference is cited in the thesis. 

However, I do not want these numbers to appear in my thesis. May I know what changes should I made?

**Comment by wang-chen** [comment]
Please delete "backref=page" at [line 171 of 'Thesis.cls'](https://github.com/wang-chen/thesis_template_ntu/blob/dde509bca4607b37414c947e41109ab1a2a536e2/Thesis.cls#L171).

**Comment by hongwai1920** [comment]
Thanks, that solves my problem.
